asyncapi/event-gateway

README.md
This PR adds a text banner at the top of the README file asking for use cases. The banner is generated through https://dummyimage.com.
This is how it looks:
=> docs: add banner asking for use cases at README

README.md
This PR adds a simple flow chart (shaped like a possible hexagonal architecture) containing the big picture of the application. 
It does not clarify that much but I had it on my Ipad since time ago so I decided to add it here.
It looks like this: ![AsyncAPI Event Gateway big picture](https://user-images.githubusercontent.com/1083296/120669755-07323e00-c490-11eb-8844-a6292b516656.jpg)
=> docs: add small flowchart about the big picture

go.mod, kafka/protocol/control_record.go, kafka/protocol/crc32_field.go, kafka/protocol/decoder.go, kafka/protocol/decompress.go, kafka/protocol/key.go, kafka/protocol/length_field.go, kafka/protocol/message.go, kafka/protocol/message_set.go, kafka/protocol/produce_request.go, kafka/protocol/record.go, kafka/protocol/record_batch.go, kafka/protocol/records.go, kafka/protocol/timestamp.go, kafka/protocol/zstd.go, kafka/proxy.go, kafka/proxy_test.go, main.go, proxy/proxy.go
This PR moves all the logic related to the Kafka proxy creation that was previously in the `main.go` file to it's own package.
It also adds a test for the message validation logic.
It also adds a new func that will implement all proxies (on its own package called `proxy`).
This change is useful for the next PR's which will use it.
=> chore: extract Kafka proxy logic to its own package

kafka/proxy.go, kafka/proxy_test.go
Tests were failing silently as no error happens when decoding goes wrong. This is on purpose so we do not break the basic proxy functionality (clients can still communicate to the brokers). 
This change fixes the payloads in the tests and changes log levels to rely by now on them, so tests will fail if decoding goes wrong.
=> fix: fix kafka proxy tests

asyncapi/document.go, asyncapi/extension.go, asyncapi/v2/decode_test.go, asyncapi/v2/v2.go, config/config.go, config/kafka.go, config/kafka_test.go, config/testdata/simple-kafka.yaml, kafka/config.go, kafka/config_test.go, kafka/proxy.go, kafka/proxy_test.go, main.go
As discussed in https://github.com/asyncapi/event-gateway/pull/15#discussion_r668118357, this PR allows to configure Kafka proxy listener by specifying the name of a server located in the provided AsyncAPI doc. 
This option restricts the number of listeners the proxy can have, so it will only open one port matching the remote port. For example, for the remote `broker.mybrokers.org:9092`, the proxy will listen at: `localhost:9092`.
Note that this won't work for brokers published as localhost, for example, `localhost:9092`. In this case, the proxy config validation will fail and it will suggest the user to set the `x-eventgateway-listener` extension or set an env var.
=> feat(config): allow configuring single listener from AsyncAPI server

asyncapi/document.go, asyncapi/v2/decode.go, asyncapi/v2/decode_test.go, asyncapi/v2/v2.go
This PR adds all main models needed for getting all required info the app needs for validating messages based on an AsyncAPI document.
Note that there are some `TODO` comments. As this is based on https://github.com/asyncapi/parser-api/blob/master/docs/v1.md and it's becoming the first implementation, there is some uncertainty around. Issues and/or PR's will be created against https://github.com/asyncapi/parser-api whenever we keep moving forward with the development but most probably once we start migrating all the `asyncapi` package to https://github.com/asyncapi/parser-go. 
TO clarify, all those TODO won't affect the behavior of this application (or at least is not expected by now).
Code needed for https://github.com/asyncapi/event-gateway/issues/10
=> feat(model): add message model and dependants

.golangci.yml, asyncapi/document.go, asyncapi/v2/decode_test.go, asyncapi/v2/v2.go, asyncapi/v2/v2_test.go, asyncapi/v2/validation.go, asyncapi/v2/validation_test.go, config/config.go, config/kafka.go, config/kafka_test.go, go.mod, go.sum, kafka/config.go, kafka/proxy.go, kafka/proxy_test.go, main.go, proxy/validation.go, proxy/validation_test.go
This PR adds the required code to validate Kafka message against a JSON Schema document, which is grabbed from the message payload declared in the AsyncAPI document.
It introduces a new error validation notification mechanism, that allows configuring a Go channel where all validation errors will flow. Now the behavior is just logging those validation errors.
You can see a demo of this feature working [here](https://cln.sh/QZg3RT)
Fixes https://github.com/asyncapi/event-gateway/issues/10
=> feat: add message validation based on schema

config/config.go, go.mod, go.sum, kafka/proxy.go, main.go, proxy/validation.go, proxy/validation_test.go
This PR adds a new WS endpoint where people can connect to and see all validation errors of all messages flowing through the gateway.
It is an early version of what the endpoint could do. By now, it lists all validation errors from **all** messages. People can kinda differentiate messages by checking, for example, the headers.
Pending to add an AsyncAPI yaml file (next pr).
Another work I will like to do is a simple static HTML that connects to the WS and shows the messages.
In the near future, it could implement filtering (by header, topic, etc), but for today, this is more than ok. 
Demo:
https://github.com/asyncapi/event-gateway/issues/23
=> feat: add websocket endpoint to receive validation errors

asyncapi/v2/validation_test.go, main.go, proxy/validation.go, proxy/validation_test.go
This PR changes the way validation errors are encoded and then sent to the WS connection. In particular, it encodes each WS message to JSON so it can become machine-readable. This is useful for automating  end-to-end tests on real infrastructure.
An example of an encoded WS message (formatted):
```json
{
"ts": "2021-08-16T12:36:12.025941+02:00",
"msg": {
"context": {
"channel": "demo"
},
"key": "c21veWEtd2FzLWhlcmU=",
"value": "eyJjb21tYW5kIjogMX0="
},
"errors": [
"command: Invalid type. Expected: string, given: integer"
]
}
```
https://github.com/asyncapi/event-gateway/issues/23
=> feat: encode ws messages to json so they become machine-readable

config/config.go, config/kafka.go, config/kafka_test.go, config/testdata/override-port-kafka.yaml, main.go
This PR does all of the following:
- Unifies Kafka proxy config logic, specially around Kafka brokers address mapping.
- Adds descriptions to all configurations, so it improves documentation.
- It prints usage of env vars when an error is related to configuration.
=> feat: reuse Kafka proxy config logic

deployments/kafka-test/main.tf, deployments/kafka-test/variables.tf
This PR creates a second Kafka topic at Aiven so it can be used for publishing events such as message validation errors, etc.
Needed for consuming those from Websockets.
https://github.com/asyncapi/event-gateway/issues/37
=> chore(infra): add second Kafka topic for validation errors

kafka/proxy.go
Context: Most of the times, kafka brokers don't have an static IP. We just have one DSN such as `kafka.myserver.org` which resolves to a broker (or load balancer) which then discovers all the broker IPs at that moment, sending that info back to the Kafka client (this is standard Kafka protocol). 
Those brokers will need to map to a local port so they can be accessed by Kafka clients. Those ports are called Dynamic listeners in our app (and in https://github.com/grepplabs/kafka-proxy).
Those ports are opened binding to localhost, however `120.0.0.1` is used as binding IP, meaning `127.0.0.1` only binds to local network interface, and won't be accessible from outside the machine. Meanwhile `0.0.0.0` binds to all network interfaces allowing to do calls to those ports from …
=> feat: default dynamic listener ip set to 0.0.0.0

config/kafka.go, config/kafka_test.go, config/testdata/invalid-same-address.yaml, docs/config/kafka.md, kafka/config.go
Fixes https://github.com/asyncapi/event-gateway/issues/50.
This PR drops the option to configure Kafka broker mappings from env vars. Instead, it forces the user to use AsyncAPI, which becomes the main config source from now on.
https://github.com/asyncapi/event-gateway/issues/50
=> feat(config): remove support for configuring kafka broker from env vars

deployments/k8s/asyncapi-event-gateway/values.yaml
This PR sets the docker image pull policy to `Always` on our K8s helm charts so on every deploy we update the Docker image.
This is useful since we are under development, so changes should be quickly propagated and tested. 
Once we fix https://github.com/asyncapi/event-gateway/issues/86, we could move that change to the `event-gateway-demo` chart instead.
=> fix: set pullPolicy to Always since we are under development phase

deployments/k8s/event-gateway-demo/event-gateway-demo.asyncapi.yaml, deployments/k8s/event-gateway-demo/templates/NOTES.txt
We are using `.com` instead of `.org` on all our services from time ago (for SEO purpose) so I'm fixing that right now. Also the event-gateway-demo is deployed and the DNS records are only added to the `.com`.
I'm taking this opportunity to fix the helper message from the chart so it prints the right service name.
=> fix: set event-gateway-demo domain extension to .com

deployments/k8s/asyncapi-event-gateway/templates/deployment.yaml, deployments/k8s/asyncapi-event-gateway/values.yaml
This PR allow users to set extra labels on the Deployment pods. Useful for custom labels or to force a Docker image pull when executing `helm upgrade` command when the Docker image tag is set to `latest` and there is no change in the chart.
In this case, users can add an extra label such as `--set asyncapi-event-gateway.deploymentExtraLabels.date=$(date +%s)` so Helm recreates the pod.
This is not yet documented but it will be in a next iteration.
=> ci: allow setting extra deployment pod labels in Helm chart

message/handler/validate.go, message/handler/validate_test.go
This PR fixes an infinite loop in the message pipeline when a message payload is not a valid JSON. As the message handler was returning an error, this was telling watermill to retry and retry. Here is a portion of the output log lines:
```bash
ERRO[2021-12-16T12:42:55+01:00] Handler returned error                        error="error validating JSON Schema for message event-gateway-demo: invalid character 'b' looking fo
r beginning of value"
ERRO[2021-12-16T12:42:55+01:00] failed to validate message. Skipping message...  error="error validating JSON Schema for message event-gateway-demo: invalid character 'b' looking
for beginning of value"
ERRO[2021-12-16T12:42:55+01:00] Handler returned error                        error="error validating JSON Schema for message …
```
=> fix: skip message when invalid JSON

README.md
It closes https://github.com/asyncapi/event-gateway/issues/23.
This PR adds documentation about the recently deployed Event-Gateway demo application, including a video recording I made today.
https://github.com/asyncapi/event-gateway/issues/23
=> docs: add docs about the demo application

Makefile
install.goreleaser.com does not exist anymore so the `make lint` script was failing trying to download `golangci-lint` binary from it. Replaced with the new script located in raw.githubusercontent.com for golangci-lint repository.
I also updated the version to a more recent one.
=> fix: fix golangci-lint download URL + update version

README.md
DigitalOcean extended support for us. 
We received $1200 until the end of this year. 
One of requirements is to make it transparent in readme what projects are hosted on DigitalOcean
=> chore: add info about digital ocean to readme
